#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Mon Jul 13 05:41:37 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade
import genPassDiag
import newUserDiag

# begin wxGlade: extracode
# end wxGlade
_ = wx.GetTranslation

class AddPassDiag(wx.Dialog):
    def __init__(self, parent,meta="",uname="",upass=""):
        # begin wxGlade: MainPannel.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL|wx.BORDER_DEFAULT|wx.CLOSE_BOX
        wx.Dialog.__init__(self,parent)
        self.text_ctrl_meta = wx.TextCtrl(self, wx.ID_ANY, meta,size=(300,-1))
        self.label_meta = wx.StaticText(self, wx.ID_ANY,label=_("Website/Application:"),style=wx.ALIGN_LEFT )
        self.text_ctrl_uname = wx.TextCtrl(self, wx.ID_ANY, uname,size=(200,-1))
        self.label_uname = wx.StaticText(self, wx.ID_ANY,label=_("Username:"),style=wx.ALIGN_LEFT)
        self.text_ctrl_upass = wx.TextCtrl(self, wx.ID_ANY, upass,size=(175,-1))
        self.label_upass = wx.StaticText(self, wx.ID_ANY,label=_("Password:"),style=wx.ALIGN_RIGHT)
        self.genpassb=wx.Button(self,wx.ID_ANY,_("Generate"))
        self.genpassdiag=genPassDiag.GenPassDiag(self)
        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON,self.OnGen,self.genpassb)

        okb=self.bsizer.GetAffirmativeButton()
        canb=self.bsizer.GetCancelButton()
        self.Bind(wx.EVT_BUTTON,self.OnOK,okb)
        self.Bind(wx.EVT_BUTTON,self.OnCancel,canb)


        self.Centre()
        self.text_ctrl_meta.SetFocus()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainPannel.__set_properties
        self.text_ctrl_meta.SetFocus()
        self.SetTitle(_("Save new credential"))
        #self.SetWindowStyle(wx.BORDER_DEFAULT)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainPannel.__do_layout
        sizer_all=wx.BoxSizer(wx.VERTICAL)
        sizer_v = wx.FlexGridSizer(3,2,5,5)
        sizer_v.Add(self.label_meta,1,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.ALL,0)
        sizer_v.Add(self.text_ctrl_meta,3,wx.ALL,0)
        sizer_v.Add(self.label_uname,0,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.TOP,5)
        sizer_v.Add(self.text_ctrl_uname,3,wx.TOP|wx.EXPAND,5)
        sizer_v.Add(self.label_upass,0,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.TOP,5)
        sizer_h0=wx.BoxSizer(wx.HORIZONTAL)
        sizer_h0.Add(self.text_ctrl_upass,0,wx.RIGHT|wx.TOP,5)
        sizer_h0.Add(self.genpassb,0,wx.ALIGN_TOP|wx.TOP,3)
        sizer_v.Add(sizer_h0)
        sizer_all.Add(sizer_v,0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.bsizer=self.CreateButtonSizer(wx.OK|wx.CANCEL)
        sizer_all.Add(self.bsizer,0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetSizer(sizer_all)
        sizer_all.Fit(self)
        self.Layout()
        # end wxGlade


    def OnGen(self,evt):
        if self.genpassdiag.ShowModal()==wx.ID_OK:
            self.text_ctrl_upass.SetValue(self.genpassdiag.passwd)

    def OnCancel(self,evt):
        evt.Skip()

    def OnOK(self,evt):
        self.uname=self.text_ctrl_uname.GetValue().strip()
        self.meta=self.text_ctrl_meta.GetValue().strip()
        self.upass=self.text_ctrl_upass.GetValue().strip()
        if self.uname=="" or self.upass=="" or self.meta=="":
            wx.MessageBox(_("Website/application/username/password can't be empty!"),_("Error"),0|wx.ICON_ERROR,self)
            return
        evt.Skip()



# end of class MainPannel

if __name__ == "__main__":
    app = wx.App()
    diag=AddPassDiag(None)
    app.SetTopWindow(diag)
    diag.ShowModal()
    app.MainLoop()
