#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Mon Jul 13 05:41:37 2015
#

import wx
import wx.propgrid as wxpg
# begin wxGlade: dependencies
import gettext
# end wxGlade

import common

# begin wxGlade: extracode
# end wxGlade
_ = wx.GetTranslation

class GenPassDiag(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainPannel.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL|wx.BORDER_DEFAULT|wx.CLOSE_BOX
        wx.Dialog.__init__(self, *args, **kwds)
        self.grid=wxpg.PropertyGrid(self,wx.ID_ANY)
        self.grid.Append(wxpg.IntProperty(_("Password Length"),"plen",value=16))
        self.grid.Append(wxpg.BoolProperty(_("Use lowercause letters"),"lowercase",value=True))
        self.grid.SetPropertyAttribute("lowercase", "UseCheckbox", True)
        self.grid.Append(wxpg.BoolProperty(_("Use Uppercase letters"),"uppercase",value=True))
        self.grid.SetPropertyAttribute("uppercase", "UseCheckbox", True)
        self.grid.Append(wxpg.BoolProperty(_("Use digits"),"digit",value=True))
        self.grid.SetPropertyAttribute("digit", "UseCheckbox", True)
        self.grid.Append(wxpg.BoolProperty(_("Use punctions"),"punction",value=True))
        self.grid.SetPropertyAttribute("punction", "UseCheckbox", True)
        self.grid.Append(wxpg.StringProperty(_("Use custom letters"),"custom",value=""))

        self.passwd=u""

        self.__set_properties()
        self.__do_layout()

        okb=self.bsizer.GetAffirmativeButton()
        canb=self.bsizer.GetCancelButton()
        self.Bind(wx.EVT_BUTTON,self.OnOK,okb)
        self.Bind(wx.EVT_BUTTON,self.OnCancel,canb)
        self.Centre()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainPannel.__set_properties
        self.SetTitle(_("Generate a password"))
        #self.SetWindowStyle(wx.BORDER_DEFAULT)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainPannel.__do_layout
        sizer_v = wx.BoxSizer(wx.VERTICAL)
        sizer_v.Add(self.grid, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.EXPAND, 5)
        #self.bsizer=common.CreateBSizer(self)
        self.bsizer=self.CreateButtonSizer(wx.OK|wx.CANCEL)
        sizer_v.Add(self.bsizer, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetSizer(sizer_v)
        sizer_v.Fit(self)
        self.Layout()
        # end wxGlade

    def OnOK(self,evt):
        c=self.grid.GetPropertyValue("custom")
        c=c.strip()
        c=c.replace(" ","")
        c=c.replace("\t","")
        self.passwd=common.genPass(self.grid.GetPropertyValue("plen"),
                                   self.grid.GetPropertyValue("digit"),
                                   self.grid.GetPropertyValue("lowercase"),
                                   self.grid.GetPropertyValue("uppercase"),
                                   self.grid.GetPropertyValue("punction"),
                                   c,
            )
        evt.Skip()



    def OnCancel(self,evt):
        evt.Skip()



# end of class MainPannel

if __name__ == "__main__":
    app = wx.App()
    diag=GenPassDiag(None)
    app.SetTopWindow(diag)
    diag.ShowModal()
    print diag.passwd
    app.MainLoop()
