#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Mon Jul 13 05:41:37 2015
#

import wx
import common

# begin wxGlade: dependencies
import gettext
# end wxGlade
import genPassDiag
import threading

# begin wxGlade: extracode
# end wxGlade
_ = wx.GetTranslation

class ListAllPassDiag(wx.Dialog):
    def __init__(self, parent,meta,uname,apc):
        # begin wxGlade: MainPannel.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL|wx.BORDER_DEFAULT|wx.CLOSE_BOX
        wx.Dialog.__init__(self,parent)
        self.meta=meta
        self.uname=uname
        self.text_ctrl_meta = wx.TextCtrl(self, wx.ID_ANY, meta,size=(300,-1),style=wx.TE_READONLY)
        self.label_meta = wx.StaticText(self, wx.ID_ANY,label=_("Website/Application:"),style=wx.ALIGN_LEFT )
        self.text_ctrl_uname = wx.TextCtrl(self, wx.ID_ANY, uname,size=(200,-1),style=wx.TE_READONLY)
        self.label_uname = wx.StaticText(self, wx.ID_ANY,label=_("Username:"),style=wx.ALIGN_LEFT)
        self.choice_upass = wx.Choice(self, wx.ID_ANY,size=(175,-1))
        self.label_upass = wx.StaticText(self, wx.ID_ANY,label=_("Password:"),style=wx.ALIGN_RIGHT)
        self.copypassb=wx.Button(self,wx.ID_ANY,_("Copy Password"))
        self.delpassb=wx.Button(self,wx.ID_ANY,_("Delete Password"))
        self.apc=apc
        self.plist=None
        self.reload()

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON,self.OnCopy,self.copypassb)
        self.Bind(wx.EVT_BUTTON,self.OnDel,self.delpassb)
        self.Bind(common.EVT_MANPASS_LOAD_DONE,self.loadDone)
        self.Bind(common.EVT_MANPASS_ERR,self.OnErr)

        self.Centre()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainPannel.__set_properties
        self.text_ctrl_meta.SetFocus()
        self.SetTitle(_("List all history passwords"))
        #self.SetWindowStyle(wx.BORDER_DEFAULT)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainPannel.__do_layout
        sizer_all=wx.BoxSizer(wx.VERTICAL)
        sizer_grid = wx.FlexGridSizer(3,2,5,5)
        sizer_grid.Add(self.label_meta,1,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.ALL,0)
        sizer_grid.Add(self.text_ctrl_meta,3,wx.ALL|wx.EXPAND,0)
        sizer_grid.Add(self.label_uname,0,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.TOP,5)
        sizer_grid.Add(self.text_ctrl_uname,3,wx.TOP|wx.EXPAND,5)
        sizer_grid.Add(self.label_upass,0,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.TOP,5)
        sizer_h0=wx.BoxSizer(wx.HORIZONTAL)
        sizer_h0.Add(self.choice_upass,0,wx.RIGHT|wx.TOP,5)
        sizer_h0.Add(self.copypassb,0,wx.ALIGN_TOP|wx.TOP,3)
        sizer_h0.Add(self.delpassb,0,wx.ALIGN_TOP|wx.TOP,3)
        sizer_grid.Add(sizer_h0)
        sizer_all.Add(sizer_grid,0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.bsizer=self.CreateButtonSizer(wx.OK|wx.CANCEL)
        sizer_all.Add(self.bsizer,0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetSizer(sizer_all)
        sizer_all.Fit(self)
        self.Layout()
        # end wxGlade

    def reload(self):
        self.choice_upass.Clear()
        self.choice_upass.Append(_("Loading..."))
        self.choice_upass.SetSelection(0)
        t=threading.Thread(target=self.apc.getAllRecodsForMeta,args=(self.meta,self.uname,None,self))
        t.daemon=True
        t.start()




    def OnCopy(self,evt):
        i=self.choice_upass.GetSelection()
        if i < len(self.plist) and not wx.TheClipboard.IsOpened():
            cdata=wx.TextDataObject()
            cdata.SetText(self.plist[i]["Pass"])
            wx.TheClipboard.Open()
            wx.TheClipboard.SetData(cdata)
            wx.TheClipboard.Close()
            self.GetParent().GetParent().StartClearTimer(self.plist[i]["Pass"])
            dlg = wx.MessageDialog(self, _('Password Copied to Clipboard'),
                           _('Done'),
                           wx.OK | wx.ICON_INFORMATION
                                                          )
        else:
            dlg = wx.MessageDialog(self,_('{Password Copy Failed'),
                           _('Error'),
                           wx.OK | wx.ICON_ERROR
                                                          )
        dlg.ShowModal()
        dlg.Destroy()

    def OnDel(self,evt):
        i=self.choice_upass.GetSelection()
        dlg=wx.MessageDialog(self, _("Are you sure to delete password rev ")+unicode(self.plist[i]['Pass_rev'])+", "+self.plist[i]['Pass_time']+" ?", _("Are you sure?"), wx.YES_NO | wx.ICON_QUESTION|wx.NO_DEFAULT)
        if dlg.ShowModal()==wx.ID_YES:
            try:
                self.apc.remove(self.meta,self.uname,self.plist[i]["Pass_rev"])
            except Exception as Err:
                wx.MessageBox(_("Unable to remove saved credential!\n")+unicode(Err),_("Error"),0|wx.ICON_ERROR,self)
                return
            self.reload()

    def loadDone(self,evt):
        self.plist=evt.plist
        self.choice_upass.Clear()
        for p in self.plist:
            self.choice_upass.Append("Rev:{rev} {date}".format(rev=p['Pass_rev'] ,date=p['Pass_time']))
        self.choice_upass.SetSelection(0)

    def OnErr(self,evt):
        wx.MessageBox(_("Updating records failed!\n")+evt.Value,_("Error"),0|wx.ICON_ERROR,self)
        self.enableMe()

# end of class MainPannel

if __name__ == "__main__":
    app = wx.App()
    diag=ListAllPassDiag(None)
    app.SetTopWindow(diag)
    diag.ShowModal()
    app.MainLoop()
