#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0 on Mon Jul 13 05:41:37 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade
import newUserDiag

# begin wxGlade: extracode
# end wxGlade
_ = wx.GetTranslation

class UnlockDiag(wx.Dialog):
    def __init__(self, parent,uname):
        # begin wxGlade: MainPannel.__init__
        #kwds["style"] = wx.TAB_TRAVERSAL|wx.BORDER_DEFAULT|wx.CLOSE_BOX
        wx.Dialog.__init__(self, parent)

        self.text_ctrl_upass = wx.TextCtrl(self, wx.ID_ANY, "",style=wx.TE_PASSWORD)
        self.label_upass = wx.StaticText(self, wx.ID_ANY,label=_("Type password of ")+uname+_(" to unlock:"),style=wx.ALIGN_RIGHT|wx.ALIGN_CENTRE_HORIZONTAL )
        self.__set_properties()
        self.__do_layout()
        self.Centre()
        self.text_ctrl_upass.SetFocus()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainPannel.__set_properties

        self.SetTitle(_("Unlock"))

        #self.SetWindowStyle(wx.BORDER_DEFAULT)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainPannel.__do_layout
        sizer_all=wx.BoxSizer(wx.VERTICAL)
        sizer_grid = wx.FlexGridSizer(2,1,5,5)
        sizer_grid.Add(self.label_upass,1,wx.FIXED_MINSIZE|wx.ALIGN_RIGHT|wx.ALL,0)
        sizer_grid.Add(self.text_ctrl_upass,3,wx.ALL|wx.EXPAND,0)
        sizer_all.Add(sizer_grid,0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        bsizer=self.CreateButtonSizer(wx.OK|wx.CANCEL)
        sizer_all.Add(bsizer, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetSizer(sizer_all)
        sizer_all.Fit(self)
        self.Layout()
        # end wxGlade



# end of class MainPannel

if __name__ == "__main__":
    app = wx.App()
    diag=UnlockDiag(None,"testuser")
    app.SetTopWindow(diag)
    diag.ShowModal()
    app.MainLoop()
